//FAÇA UM PROGAMA EM C QUE LEIA O TAMANHO DA MATRIZ [MxN] E LEIA OS VALORES PARA
//PREENCHER TOTALMENTE A MATRIZ
//EM SEQUIDA, CALCULE A SOMA DOS VALORES:
// 1- DA DIAGONAL PRINCIPAL
// 2- DA TRIANGULAR SUPERIOR
// 3- DA TRIANGULAR INFERIOR
// 4- DA DIAGONAL SECUDARIA

#include <stdio.h>

int main(){
    

    return 0;
}